language: java

jdk:
  - oraclejdk8

branches:
  only:
  - master

jobs:
  include:
    - stage: build
      script:
        - ./gradlew build

notifications:
  email:
    - adityajadhav537@gmail.com
