language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

branches:
  only:
  - master

jobs:
  include:
    - stage: build
      script:
        - ./gradlew build

notifications:
  email:
    - adityajadhav537@gmail.com
